//------------------------------------------------------------------------
// Copyright(c) 2024 Jonathan Abbott
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake
#include "projectversion.h"

#define stringOriginalFilename "JaGain.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription "JaGain VST3 (64Bit)"
#else
#define stringFileDescription "JaGain VST3"
#endif
#define stringCompanyName "\0"
#define stringLegalCopyright "Copyright(c) 2024 Jonathan Abbott"
#define stringLegalTrademarks "VST is a trademark of Steinberg Media Technologies GmbH"
